import { Prisma } from "@prisma/client";

export const seedVenues: Prisma.VenueCreateInput[] = [
  {
    name: "The Wente Estate",
    slug: "the-wente-estate",
    street: "5565 Tesla Rd",
    city: "Livermore",
    state: "CA",
    zip: "94550",
    website: "https://wentevineyards.com/weddings",
    phone: "(925) 456-2305",
    venueType: "Vineyard & Winery",
    styleTags: ["Romantic", "Rustic Elegant", "Wine Country"],
    minGuests: 50,
    maxGuests: 250,
    seatedMax: 250,
    standingMax: 300,
    baseRentalMin: 8000,
    baseRentalMax: 18000,
    priceTier: "luxury",
    perHeadMin: 85,
    perHeadMax: 145,
    depositPercent: 25,
    peakPricing: true,
    offPeakDiscount: true,
    hasBridalSuite: true,
    hasGroomSuite: true,
    hasOutdoorSpace: true,
    hasIndoorSpace: true,
    tablesChairsIncluded: true,
    avIncluded: true,
    lightingIncluded: true,
    cateringKitchen: true,
    barSetup: true,
    onSiteCoordinator: true,
    preferredVendorList: true,
    outsideVendorsAllowed: false,
    inHouseCateringRequired: true,
    byobPolicy: "Not allowed — in-house wine and spirits only",
    setupHours: 4,
    teardownHours: 2,
    earliestStart: "10:00 AM",
    latestEnd: "11:00 PM",
    noiseOrdinance: "Outdoor music must end by 10:00 PM",
    nearbyLodging: true,
    leadTimeMonths: 12,
    cancellationPolicy: "50% refund if cancelled 6+ months in advance",
    photoTags: ["Vineyard", "Outdoor", "Garden", "Rustic"],
    naturalLight: "excellent",
    adaCompliant: true,
    googleRating: 4.9,
    googleReviews: 187,
    primaryPhotoUrl: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=800&h=500&fit=crop",
    photoCount: 47,
    completenessScore: 95,
    isPublished: true,
    description:
      "Stunning vineyard setting with indoor and outdoor ceremony options in the heart of Livermore Valley wine country. The Wente Estate offers sweeping vineyard views, an elegant indoor ballroom, and a wine cave perfect for cocktail hour.",
  },
  {
    name: "Elliston Vineyards",
    slug: "elliston-vineyards",
    street: "463 Kilkare Rd",
    city: "Sunol",
    state: "CA",
    zip: "94586",
    website: "https://elliston.com",
    phone: "(925) 862-2377",
    venueType: "Garden & Vineyard",
    styleTags: ["Romantic", "Garden", "Boho"],
    minGuests: 30,
    maxGuests: 150,
    seatedMax: 150,
    standingMax: 200,
    baseRentalMin: 5500,
    baseRentalMax: 10000,
    priceTier: "moderate",
    perHeadMin: 70,
    perHeadMax: 110,
    depositPercent: 25,
    peakPricing: true,
    hasBridalSuite: true,
    hasGroomSuite: false,
    hasOutdoorSpace: true,
    hasIndoorSpace: true,
    tablesChairsIncluded: true,
    cateringKitchen: true,
    barSetup: true,
    onSiteCoordinator: false,
    outsideVendorsAllowed: true,
    setupHours: 3,
    teardownHours: 2,
    earliestStart: "10:00 AM",
    latestEnd: "10:00 PM",
    nearbyLodging: false,
    leadTimeMonths: 9,
    photoTags: ["Garden", "Hillside", "Intimate", "Vineyard"],
    naturalLight: "excellent",
    adaCompliant: false,
    googleRating: 4.7,
    googleReviews: 93,
    primaryPhotoUrl: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=800&h=500&fit=crop",
    photoCount: 28,
    completenessScore: 80,
    isPublished: true,
    description:
      "Intimate hillside vineyard with a romantic garden chapel and sweeping valley views. Elliston is beloved for its fairy-tale setting and relaxed, personal atmosphere.",
  },
  {
    name: "Casa Real at Ruby Hill",
    slug: "casa-real-ruby-hill",
    street: "1 Vineyard Ave",
    city: "Pleasanton",
    state: "CA",
    zip: "94566",
    website: "https://casarealwinery.com",
    phone: "(925) 931-9463",
    venueType: "Ballroom & Garden",
    styleTags: ["Elegant", "Romantic", "Modern"],
    minGuests: 100,
    maxGuests: 400,
    seatedMax: 400,
    standingMax: 500,
    baseRentalMin: 12000,
    baseRentalMax: 25000,
    priceTier: "luxury",
    perHeadMin: 100,
    perHeadMax: 180,
    depositPercent: 30,
    peakPricing: true,
    offPeakDiscount: true,
    allInclusive: true,
    hasBridalSuite: true,
    hasGroomSuite: true,
    hasOutdoorSpace: true,
    hasIndoorSpace: true,
    tablesChairsIncluded: true,
    linensIncluded: true,
    avIncluded: true,
    lightingIncluded: true,
    cateringKitchen: true,
    barSetup: true,
    onSiteCoordinator: true,
    preferredVendorList: true,
    outsideVendorsAllowed: false,
    inHouseCateringRequired: true,
    setupHours: 5,
    teardownHours: 2,
    earliestStart: "10:00 AM",
    latestEnd: "11:00 PM",
    noiseOrdinance: "Indoor music only after 10:00 PM",
    nearbyLodging: true,
    leadTimeMonths: 18,
    cancellationPolicy: "50% refund if cancelled 9+ months in advance",
    photoTags: ["Ballroom", "Mediterranean", "Garden", "Elegant"],
    naturalLight: "good",
    adaCompliant: true,
    elevatorAccess: true,
    googleRating: 4.8,
    googleReviews: 241,
    primaryPhotoUrl: "https://images.unsplash.com/photo-1478146059778-26028b07395a?w=800&h=500&fit=crop",
    photoCount: 62,
    completenessScore: 98,
    isPublished: true,
    description:
      "Elegant Mediterranean-inspired estate with a grand ballroom and manicured outdoor gardens. Casa Real is one of the premier wedding destinations in the East Bay, offering full-service luxury packages.",
  },
  {
    name: "The Bridges Golf Club",
    slug: "the-bridges-golf-club",
    street: "9000 S Gale Ridge Rd",
    city: "San Ramon",
    state: "CA",
    zip: "94582",
    website: "https://thebridgesgolf.com",
    phone: "(925) 735-4253",
    venueType: "Golf Club & Terrace",
    styleTags: ["Modern", "Elegant", "Garden"],
    minGuests: 50,
    maxGuests: 200,
    seatedMax: 200,
    standingMax: 250,
    baseRentalMin: 9000,
    baseRentalMax: 16000,
    priceTier: "luxury",
    perHeadMin: 90,
    perHeadMax: 140,
    depositPercent: 25,
    peakPricing: true,
    hasBridalSuite: true,
    hasGroomSuite: true,
    hasOutdoorSpace: true,
    hasIndoorSpace: true,
    tablesChairsIncluded: true,
    avIncluded: true,
    cateringKitchen: true,
    barSetup: true,
    onSiteCoordinator: true,
    preferredVendorList: true,
    outsideVendorsAllowed: false,
    inHouseCateringRequired: true,
    setupHours: 4,
    teardownHours: 2,
    earliestStart: "10:00 AM",
    latestEnd: "11:00 PM",
    nearbyLodging: true,
    leadTimeMonths: 12,
    photoTags: ["Golf Club", "Terrace", "Views", "Modern"],
    naturalLight: "excellent",
    adaCompliant: true,
    googleRating: 4.6,
    googleReviews: 78,
    primaryPhotoUrl: "https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?w=800&h=500&fit=crop",
    photoCount: 34,
    completenessScore: 85,
    isPublished: true,
    description:
      "Scenic golf club terrace overlooking rolling greens, perfect for a modern outdoor celebration. The Bridges offers stunning hill views and impeccable service.",
  },
  {
    name: "Blackhawk Country Club",
    slug: "blackhawk-country-club",
    street: "599 Blackhawk Club Dr",
    city: "Danville",
    state: "CA",
    zip: "94506",
    website: "https://blackhawkcc.org",
    phone: "(925) 736-6550",
    venueType: "Country Club",
    styleTags: ["Elegant", "Romantic", "Vintage"],
    minGuests: 80,
    maxGuests: 300,
    seatedMax: 300,
    standingMax: 400,
    baseRentalMin: 11000,
    baseRentalMax: 22000,
    priceTier: "luxury",
    perHeadMin: 95,
    perHeadMax: 160,
    depositPercent: 30,
    peakPricing: true,
    hasBridalSuite: true,
    hasGroomSuite: true,
    hasOutdoorSpace: true,
    hasIndoorSpace: true,
    tablesChairsIncluded: true,
    linensIncluded: true,
    avIncluded: true,
    lightingIncluded: true,
    cateringKitchen: true,
    barSetup: true,
    onSiteCoordinator: true,
    outsideVendorsAllowed: false,
    inHouseCateringRequired: true,
    setupHours: 5,
    teardownHours: 2,
    latestEnd: "11:00 PM",
    nearbyLodging: true,
    leadTimeMonths: 14,
    photoTags: ["Country Club", "Mountain Views", "Ballroom", "Elegant"],
    naturalLight: "good",
    adaCompliant: true,
    googleRating: 4.8,
    googleReviews: 134,
    primaryPhotoUrl: "https://images.unsplash.com/photo-1510076857177-7470076d4098?w=800&h=500&fit=crop",
    photoCount: 41,
    completenessScore: 92,
    isPublished: true,
    description:
      "Prestigious Danville country club with sweeping mountain views and a refined indoor ballroom. Blackhawk is synonymous with sophistication and timeless elegance.",
  },
  {
    name: "The Purple Orchid Inn",
    slug: "the-purple-orchid-inn",
    street: "4549 Cross Rd",
    city: "Livermore",
    state: "CA",
    zip: "94550",
    website: "https://purpleorchid.com",
    phone: "(925) 606-8855",
    venueType: "Boutique Estate",
    styleTags: ["Rustic", "Boho", "Intimate"],
    minGuests: 30,
    maxGuests: 100,
    seatedMax: 100,
    standingMax: 120,
    baseRentalMin: 4500,
    baseRentalMax: 8000,
    priceTier: "moderate",
    perHeadMin: 60,
    perHeadMax: 100,
    depositPercent: 20,
    hasBridalSuite: true,
    hasOutdoorSpace: true,
    hasIndoorSpace: true,
    tablesChairsIncluded: true,
    cateringKitchen: true,
    outsideVendorsAllowed: true,
    setupHours: 3,
    teardownHours: 2,
    earliestStart: "10:00 AM",
    latestEnd: "10:00 PM",
    nearbyLodging: true,
    leadTimeMonths: 6,
    photoTags: ["Olive Grove", "Rustic Barn", "Intimate", "Boho"],
    naturalLight: "excellent",
    adaCompliant: false,
    googleRating: 4.5,
    googleReviews: 62,
    primaryPhotoUrl: "https://images.unsplash.com/photo-1532712938310-34cb3982ef74?w=800&h=500&fit=crop",
    photoCount: 19,
    completenessScore: 72,
    isPublished: true,
    description:
      "Charming olive grove estate with a rustic barn and intimate courtyard for smaller weddings. The Purple Orchid is perfect for couples who want a personal, storybook setting.",
  },
  {
    name: "Sequoia Mansion",
    slug: "sequoia-mansion",
    city: "Pleasanton",
    state: "CA",
    zip: "94566",
    venueType: "Historic Estate",
    styleTags: ["Vintage", "Romantic", "Elegant"],
    minGuests: 50,
    maxGuests: 180,
    seatedMax: 180,
    baseRentalMin: 7000,
    baseRentalMax: 13000,
    priceTier: "moderate",
    perHeadMin: 75,
    perHeadMax: 120,
    depositPercent: 25,
    hasBridalSuite: true,
    hasOutdoorSpace: true,
    hasIndoorSpace: true,
    tablesChairsIncluded: true,
    cateringKitchen: true,
    outsideVendorsAllowed: true,
    setupHours: 4,
    teardownHours: 2,
    latestEnd: "10:00 PM",
    nearbyLodging: true,
    leadTimeMonths: 9,
    photoTags: ["Victorian", "Historic", "Garden", "Romantic"],
    naturalLight: "good",
    adaCompliant: false,
    googleRating: 4.7,
    googleReviews: 108,
    primaryPhotoUrl: null,
    photoCount: 0,
    completenessScore: 60,
    isPublished: true,
    description:
      "A lovingly restored Victorian mansion with original architecture and lush private gardens. Sequoia Mansion offers a one-of-a-kind historic backdrop for your wedding day.",
  },
  {
    name: "Dublin Ranch Golf Course",
    slug: "dublin-ranch-golf-course",
    street: "5900 Signal Hill Dr",
    city: "Dublin",
    state: "CA",
    zip: "94568",
    website: "https://dublinranchgolf.com",
    phone: "(925) 556-7040",
    venueType: "Golf Club & Lawn",
    styleTags: ["Modern", "Garden", "Casual Elegant"],
    minGuests: 40,
    maxGuests: 150,
    seatedMax: 150,
    baseRentalMin: 6000,
    baseRentalMax: 11000,
    priceTier: "moderate",
    perHeadMin: 65,
    perHeadMax: 105,
    depositPercent: 25,
    hasBridalSuite: false,
    hasOutdoorSpace: true,
    hasIndoorSpace: true,
    tablesChairsIncluded: true,
    barSetup: true,
    cateringKitchen: true,
    outsideVendorsAllowed: false,
    inHouseCateringRequired: true,
    setupHours: 3,
    teardownHours: 1,
    latestEnd: "10:30 PM",
    nearbyLodging: true,
    leadTimeMonths: 8,
    photoTags: ["Golf Course", "Panoramic", "Lawn", "Hills"],
    naturalLight: "excellent",
    adaCompliant: true,
    googleRating: 4.4,
    googleReviews: 45,
    primaryPhotoUrl: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=800&h=500&fit=crop",
    photoCount: 22,
    completenessScore: 75,
    isPublished: true,
    description:
      "Casual yet elegant golf course venue with open lawn ceremony space and panoramic East Bay hills. A great value option for mid-sized weddings in Dublin.",
  },
  {
    name: "Shadow Cliff Regional Park",
    slug: "shadow-cliff-regional-park",
    street: "2500 Dublin Canyon Rd",
    city: "Pleasanton",
    state: "CA",
    zip: "94566",
    website: "https://ebparks.org/parks/shadow-cliffs",
    phone: "(888) 327-2757",
    venueType: "Outdoor / Park",
    styleTags: ["Garden", "Boho", "Rustic"],
    minGuests: 20,
    maxGuests: 120,
    seatedMax: 120,
    baseRentalMin: 2500,
    baseRentalMax: 5000,
    priceTier: "budget",
    depositPercent: 50,
    hasOutdoorSpace: true,
    hasIndoorSpace: false,
    tablesChairsIncluded: false,
    outsideVendorsAllowed: true,
    setupHours: 2,
    teardownHours: 1,
    earliestStart: "9:00 AM",
    latestEnd: "8:00 PM",
    noiseOrdinance: "All events must end by 8:00 PM",
    nearbyLodging: false,
    leadTimeMonths: 3,
    photoTags: ["Lakeside", "Natural", "Outdoor", "Park"],
    naturalLight: "excellent",
    adaCompliant: true,
    googleRating: 4.3,
    googleReviews: 38,
    primaryPhotoUrl: null,
    photoCount: 0,
    completenessScore: 45,
    isPublished: true,
    description:
      "Natural lakeside setting with gorgeous open-air facilities and the most affordable pricing in the Tri-Valley. Ideal for intimate outdoor ceremonies with a laid-back vibe.",
  },
  {
    name: "Crow Canyon Country Club",
    slug: "crow-canyon-country-club",
    street: "711 Silver Lake Dr",
    city: "Danville",
    state: "CA",
    zip: "94526",
    website: "https://crowcanyon.org",
    phone: "(925) 735-9546",
    venueType: "Country Club & Garden",
    styleTags: ["Elegant", "Modern", "Garden"],
    minGuests: 60,
    maxGuests: 250,
    seatedMax: 250,
    standingMax: 300,
    baseRentalMin: 10500,
    baseRentalMax: 20000,
    priceTier: "luxury",
    perHeadMin: 88,
    perHeadMax: 150,
    depositPercent: 25,
    peakPricing: true,
    hasBridalSuite: true,
    hasGroomSuite: false,
    hasOutdoorSpace: true,
    hasIndoorSpace: true,
    tablesChairsIncluded: true,
    linensIncluded: true,
    avIncluded: true,
    cateringKitchen: true,
    barSetup: true,
    onSiteCoordinator: true,
    outsideVendorsAllowed: false,
    inHouseCateringRequired: true,
    setupHours: 4,
    teardownHours: 2,
    latestEnd: "11:00 PM",
    nearbyLodging: true,
    leadTimeMonths: 12,
    photoTags: ["Tented Terrace", "Garden", "Country Club", "Elegant"],
    naturalLight: "good",
    adaCompliant: true,
    googleRating: 4.7,
    googleReviews: 89,
    primaryPhotoUrl: "https://images.unsplash.com/photo-1532712938310-34cb3982ef74?w=800&h=500&fit=crop",
    photoCount: 31,
    completenessScore: 88,
    isPublished: true,
    description:
      "Elegant Danville club with a stunning tented terrace, manicured grounds, and full-service catering. Crow Canyon combines country club prestige with warm California hospitality.",
  },
];
